# Generated by Django 5.0.7 on 2024-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="register_number",
            field=models.CharField(max_length=12),
        ),
    ]
