# Generated by Django 5.0.7 on 2024-12-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="email",
        ),
    ]
