# Generated by Django 5.0.7 on 2024-08-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
