# Generated by Django 5.0.7 on 2024-12-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendanceapp", "0002_remove_staff_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="register_number",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
