# Generated by Django 5.0.7 on 2024-07-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("department", models.CharField(max_length=4)),
                ("semester", models.CharField(max_length=4)),
                ("section", models.CharField(max_length=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        choices=[
                            ("SNH", "Science and Humanities"),
                            ("IT", "Information Technology"),
                            ("CSE", "Computer Science and Engineering"),
                            ("CSBS", "Computer Science and Business Systems"),
                            ("ECE", "Electronics and communication Engineering"),
                            ("AIML", "Artificial Intelligence and Machine Learning"),
                        ],
                        max_length=4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("I Year", "1st Year"),
                            ("II Year", "2nd Year"),
                            ("III Year", "3rd Year"),
                            ("IV Year", "4th Year"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("I", "1st Semester"),
                            ("II", "2nd Semester"),
                            ("III", "3rd Semester"),
                            ("IV", "4th Semester"),
                            ("V", "5th Semester"),
                            ("VI", "6th Semester"),
                            ("VII", "7th Semester"),
                            ("VIII", "8th Semester"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("A", "A Section"),
                            ("B", "B Section"),
                            ("C", "C Section"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="attendanceapp.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "Class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="attendanceapp.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("register_number", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("Hosteller", "Hosteller"),
                            ("Dayscholar", "Dayscholar"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "Class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="attendanceapp.class",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendanceapp.attendance",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="attendanceapp.student",
                    ),
                ),
            ],
        ),
    ]
